package.json
src/app.controller.ts
src/app.service.ts
src/dto/GetHomeScreenMetric.dto.ts
src/dto/GetMentorDetails.dto.ts
src/dto/UpdateMentorPin.dto.ts
src/enums.ts
src/main.ts
yarn.lock

Mentor details and metadata apis

---

README.md
src/app.controller.spec.ts
src/app.controller.ts
src/app.service.ts
src/dto/CreateAssessmentVisitResult.dto.ts
src/enums.ts

- Added `GET /api/actor/dashboard-overview` endpoint for teacher home overview
- Added relevant Enums as app-level constants
- Added response types as app-level constants
Closes #15

Teacher Home Overview KPIs

---

src/app.controller.ts
src/app.service.ts
src/dto/CreateMentor.dto.ts
src/dto/CreateMentorOld.dto.ts
src/dto/UpsertMentorToken.dto.ts

Reference: https://stackoverflow.com/questions/18470588/in-rest-is-post-or-put-best-suited-for-upsert-operation & https://www.prisma.io/docs/concepts/components/prisma-client/crud#update-or-create-records

Adding API to upsert mentor tokens

---

src/app.controller.ts

Kindly ensure this does not reach prod.

[#42] Adding mocks for school students

---

prisma/schema.prisma
src/app.controller.ts
src/app.service.ts
src/dto/CreateBotTelemetry.dto.ts
src/dto/GetMentorBotsWithAction.dto.ts
src/main.ts

Add apis to set and get mentor bot telemetry.

Adding APIs to handle mentor bot telemetry 

---

src/app.controller.spec.ts
src/app.controller.ts
src/app.service.ts
src/auth/admin-jwt.guard.ts
src/auth/auth-jwt.guard.ts
src/auth/auth-jwt.strategy.ts
src/auth/auth.module.ts
src/interceptors/mentor.interceptor.ts
src/modules/etag/etag.module.ts
src/modules/etag/etag.service.spec.ts
src/school/school.controller.spec.ts
src/school/school.controller.ts
src/school/school.service.spec.ts
src/school/school.service.ts

Feedbacks #48

---

prisma/schema.prisma
src/app.service.ts

Assessments: dumping into hypertable as well

---

package.json
prisma/schema.prisma
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/CreateAssessmentCycle.ts
src/admin/dto/CreateAssessmentCycleDistrictExaminerMapping.ts
src/admin/dto/CreateAssessmentCycleDistrictSchoolMapping.ts
src/admin/dto/CycleIdValidateDto.ts
src/admin/dto/InvalidateExaminerCycleAssessments.dto.ts
src/app.controller.ts
src/app.service.ts
src/enums.ts
src/school/school.controller.ts
yarn.lock

Admin: Cycle creation, school<>district<>examiner mapping APIs

---

src/admin/admin.controller.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/auth/auth.validator.ts
src/dto/AssessmentCycleValidator.dto.ts
src/dto/GetSchoolStatus.dto.ts
src/dto/GetSchoolStudentsResult.dto.ts
src/enums.ts
src/i18n/en/common.json
src/i18n/hi/common.json
src/processors/calculate-examiner-cycle-udise-result.processor.ts
src/school/school.controller.ts
src/school/school.service.ts
src/school/school.service.v2.ts
src/school/student.service.ts

Examiner <> Cycle <> Student flow APIs

---

package.json
prisma/schema.prisma
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/CreateAssessmentCycle.ts
src/admin/dto/CreateAssessmentCycleDistrictExaminerMapping.ts
src/admin/dto/CreateAssessmentCycleDistrictSchoolMapping.ts
src/admin/dto/CycleIdValidateDto.ts
src/admin/dto/InvalidateExaminerCycleAssessments.dto.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/auth/auth.validator.ts
src/dto/AssessmentCycleValidator.dto.ts
src/dto/GetSchoolStatus.dto.ts
src/dto/GetSchoolStudentsResult.dto.ts
src/enums.ts
src/i18n/en/common.json
src/i18n/hi/common.json
src/processors/calculate-examiner-cycle-udise-result.processor.ts
src/school/school.controller.ts
src/school/school.service.ts
src/school/school.service.v2.ts
src/school/student.service.ts
yarn.lock

Final PR with all the changes into prod.

Examiner <> Students Flow

---

src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/MentorInfoDto.ts

Related to https://github.com/Mission-Prerna/prerna-lakshya-app/issues/287
- Clear Mentor Detail Cache
- Clear Mentor List Cache
- Clear Metadata Cache
for a list of mentor phone numbers.

feat: admin APIs to delete mentor and metadata cache

---

prisma/schema.prisma
src/admin/admin.service.ts
src/admin/dto/CreateAssessmentCycleDistrictSchoolMapping.ts
src/app.service.ts
src/school/school.service.v2.ts

fix: remove district id from assessment school mapping API

---

prisma/schema.prisma
src/app.controller.ts
src/app.service.ts

Linked to https://github.com/Mission-Prerna/prerna-lakshya-app/issues/316

Add API to return mentor bots

---

src/admin/admin.service.ts
src/app.controller.ts
src/dto/CreateMentorSegmentRequest.dto.ts

API doc PR: https://github.com/Mission-Prerna/api-collection/pull/1

Create API to map mentors to a segment

---

src/admin/admin.service.ts

Set was not printing in the json response.

Hotfix: Valid phones not showing up in mentor segment mapping api

---

.env.sample
src/admin/admin.service.ts

Tested locally for existing examiners and creating new examiners.

Temp fix examiner default cycle

---

.env.sample
src/admin/admin.service.ts

* [TEMP-FIX] Add cycles to examiner logins
* Move to config driven default cycle.
* Add skip duplicates.
* add support for default cycle id in examiner creation
---------

Temp fix examiner default cycle (#84)

---

src/school/school.service.v2.ts

Bug Report - https://discord.com/channels/959457910604333107/961521135059599380/1180054375104782367

Move to next year when month = 12 for the last day timestamp

---

src/school/school.service.v2.ts

fix: handle edge case when month == 12

---

prisma/schema.prisma
src/admin/admin.service.ts
src/admin/dto/InvalidateExaminerCycleAssessments.dto.ts
src/app.service.ts
src/school/school.service.v2.ts

Migrations PR : https://github.com/Mission-Prerna/nl-hasura-migrations/pull/3

feat: allow re-assessments for examiners in a cyle id

---

prisma/schema.prisma
src/admin/admin.service.ts
src/admin/dto/InvalidateExaminerCycleAssessments.dto.ts
src/app.controller.ts
src/app.service.ts
src/school/school.service.v2.ts

- Restructure School LIst API
- ReAssessment flows

Release v3.4.0

---

src/queries.template.ts

Update templates for quarter tables.

update query template

---

src/admin/admin.service.ts
src/app.service.ts
src/school/school.service.ts
src/school/school.service.v2.ts
src/school/student.service.ts

Use template variables in unsafe queries with user inputs. More on this https://www.prisma.io/docs/orm/prisma-client/queries/raw-database-access/raw-queries#queryrawunsafe

Remove SQL injections by using postgres template variables

---

.env.sample
package.json
src/auth/auth.controller.spec.ts
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.spec.ts
src/auth/auth.service.ts
yarn.lock

Context: https://github.com/Mission-Prerna/PrernaLakshyaBackend/issues/72
1. SendOTP - returns the same response as `/api/sendOTP`
```
curl --location --request POST 'http://128.199.28.17:3000/auth/sendOTP?phone=6307422471&errorMessage=Mobile%20number%20could%20not%20be%20verified.%20Please%20get%20in%20touch%20with%20the%20DC%20in%20your%20District%27s%20BSA%20office%20if%20your%20number%20is%20not%20registered%20on%20the%20Prerna%20Portal.' \
--header 'x-application-id: 320b020a-3d84-4d8a-a191-da4e972c2951'
```
2. Verify OTP - returns the same response as `/api/login` when success else failed response of `/api/verifyOTP`
```
curl --location --request POST 'http://128.199.28.17:3000/auth/verifyOTP?phone=6307422471&otp=7465' \
--header 'x-application-id: …
```

Refactor login flow

---

.github/workflows/nl-api-test-suite.yml

This pull request introduces GitHub Actions for the automation of Postman collection test cases. The inclusion of these automated tests enhances the project's testing infrastructure, ensuring the reliability and correctness of the API functionalities.

[Feature/Enhancement]: Added GitHub Actions for Postman Collection Tests

---

src/app.service.ts

Wrong positioning of params led to school_list being empty

fix position of params

---

src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/MentorInfoDto.ts
src/app.service.ts
src/enums.ts

We are moving metadata to actor-specific, changing the metadata cache to actor-specific so it will not conflict to other actors metadata, and same with metadata cache cleaning logic also.

Metadata cache fix

---

package.json
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/interceptors/zip-file-upload.interceptor.ts
yarn.lock

Ticket:- https://github.com/Mission-Prerna/prerna-lakshya-app/issues/439

Zip file form id update

---

src/app.controller.ts
src/dto/CreateAssessmentVisitResult.dto.ts
src/school/school.service.v2.ts

Ticket:- https://github.com/Mission-Prerna/prerna-lakshya-app/issues/440

fix: actor_id in submitting assessment and retrival of students result for mentor

---

src/school/school.service.v2.ts

Fix for Bug: Count of total student nipun is incorrect in teacher assessment history

fix: nipun student count in students result summary

---

src/app.service.ts
src/enums.ts

Fix:-  average assessment time for the mentor home screen.

fix: average time of assessment for mentor

---

src/admin/admin.service.ts

logs & sentry added in student APIs for debugging

fix: logs added in student APIs

---

src/admin/admin.service.ts

🍒 fix: logs & sentry added in student APIs

🍒 fix: logs added in student APIs (#249)

---

src/admin/admin.service.ts

fix: students crud apis logs updated to have a common word for filtering logs

fix: students crud apis logs updated to have a common word for filtering

---

src/admin/admin.service.ts
src/app.service.ts
src/enums.ts
src/school/school.service.v2.ts

Prod deployment for :- fix: average time of assessment for mentor & teacher insight nipun count

fix: average time of assessment for mentor & teacher insight nipun count

---

prisma/schema.prisma
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/CreateSchoolBlacklist.dto.ts
src/app.service.ts
src/interceptors/sentry.interceptor.ts

actor_school_blacklist table  created

feat: actor_school_blacklist table

---

src/app.service.ts

Ignoring assessment submission after udise is blacklisted for the actor

feat: Ignoring assessment submission after udise is blacklisted for the actor

---

prisma/schema.prisma
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/CreateSchoolBlacklist.dto.ts
src/app.service.ts
src/interceptors/sentry.interceptor.ts
src/school/school.service.v2.ts
src/school/student.service.ts

Prod deployment (v3.8.0) of feature:- Actor-School blacklisting & other fixes.

Prod deployment v3.8.0

---

src/app.service.ts

fix: added student ids in mentor insights

fix: added student ids in mentor insights

---

src/app.service.ts

fix: added student ids in mentor insights

fix: added student ids in mentor insights (#276)

---

src/admin/admin.service.ts
src/app.service.ts
src/school/school.service.v2.ts
src/school/student.service.ts

fix: mentor cache and assessment timestamp return format

fix: mentor cache and assessment timestamp return format

---

prisma/schema.prisma
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/admin/dto/CwsnStudents.dto.ts
src/app.service.ts

PROD deployment v4.1.0 for CWSN

PROD deployment v4.1.0 for CWSN

---

src/admin/admin.service.ts
src/dto/CreateMentor.dto.ts
src/dto/CreateMentorOld.dto.ts

fix: added is_active in mentor create API

Prod deploy v4.1.1
